import { Faction, Role } from "./types";

export const ROLES: Role[] = [
  // ── Miasto ───────────────────────────────────────────────────────────────
  {
    id: "szeryf",
    name: "Szeryf",
    faction: "miasto",
    tier: "kluczowa",
    nightUse: "co-noc",
    jawne: true,
    selfTarget: false,
    desc: "Póki szeryf żyje, można nie przyjąć pojedynku. Co noc (również zerowej) zamyka jedną osobę w więzieniu — ta nie budzi się i nie może zginąć. Jeśli zamknięta osoba miała posążek, szeryf go przejmuje; jeśli dotrwa z nim do końca nocy, miasto wygrywa.",
  },
  {
    id: "burmistrz",
    name: "Burmistrz",
    faction: "miasto",
    tier: "zwykla",
    nightUse: "brak",
    selfTarget: true,
    desc: "W dowolnym momencie może odkryć kartę. Robiąc to przy skazywaniu na powieszenie, ułaskawia wieszaną osobę (nikt nie wisi w zamian). Może ułaskawić sam siebie.",
  },
  {
    id: "dziwka",
    name: "Dziwka",
    faction: "miasto",
    tier: "kluczowa",
    nightUse: "zerowa",
    selfTarget: false,
    desc: "Wyłącznie zerowej nocy wybiera klienta. Poznaje jego kartę, a on dowiaduje się, kto jest dziwką.",
  },
  {
    id: "pastor",
    name: "Pastor",
    faction: "miasto",
    tier: "zwykla",
    nightUse: "co-noc",
    desc: "Co noc (również zerowej) spowiada wybraną osobę i poznaje jej frakcję. Spowiadany o niczym nie wie.",
  },
  {
    id: "dobry-rewolwerowiec",
    name: "Dobry rewolwerowiec",
    faction: "miasto",
    tier: "kluczowa",
    nightUse: "brak",
    desc: "Jeśli wynik pojedynku z nierewolwerowcem jest inny niż jego zwycięstwo, Manitou i tak ogłasza zwycięstwo rewolwerowca. Pojedynek dwóch rewolwerowców przebiega normalnie.",
  },
  {
    id: "opoj",
    name: "Opój",
    faction: "miasto",
    tier: "tradycyjna",
    nightUse: "dwa-razy",
    jawne: true,
    desc: "Dwa razy w grze zabiera kogoś na wódkę — ta osoba nie budzi się tej nocy, ale można ją zabić, przeszukać itd.",
  },
  {
    id: "ochroniarz",
    name: "Ochroniarz",
    faction: "miasto",
    tier: "zwykla",
    nightUse: "co-noc",
    jawne: true,
    selfTarget: false,
    desc: "Co noc chroni inną osobę — nie może ona zostać zabita (można ją okraść, spowiadać, spić). Nie chroni siebie ani tej samej osoby dwie noce z rzędu. Gdy zginie w nocy, ochrona przestaje działać.",
  },
  {
    id: "poborca",
    name: "Poborca podatków",
    faction: "miasto",
    tier: "zwykla",
    nightUse: "raz",
    desc: "Raz w grze dowiaduje się od Manitou, kto w tej chwili posiada posążek. Posążek może jeszcze zmienić właściciela tej nocy.",
  },
  {
    id: "lekarz",
    name: "Lekarz",
    faction: "miasto",
    tier: "kontrowersyjna",
    nightUse: "raz",
    selfTarget: false,
    desc: "Raz w grze wskrzesza świeżo zmarłą osobę, zanim odkryta zostanie jej karta (śmierć w pojedynku lub w nocy, nie powieszenie). Działa tajnie.",
  },
  {
    id: "hazardzista",
    name: "Hazardzista",
    faction: "miasto",
    tier: "kontrowersyjna",
    nightUse: "raz",
    jawne: true,
    desc: "Raz w grze, od drugiej nocy, zaczyna rosyjską ruletkę. Wskazuje osobę: jeśli to obywatel miasta — ginie hazardzista; jeśli nie — ginie wskazany, a hazardzista wskazuje kolejnego. Przerywa dopiero, gdy zginie albo zdobędzie posążek.",
  },
  {
    id: "agent",
    name: "Agent ubezpieczeniowy",
    faction: "miasto",
    tier: "zwykla",
    nightUse: "brak",
    desc: "W dowolnym momencie gry może ujawnić, że jest agentem ubezpieczeniowym.",
  },
  {
    id: "sedzia",
    name: "Sędzia",
    faction: "miasto",
    tier: "kontrowersyjna",
    nightUse: "raz",
    selfTarget: true,
    desc: "Raz w grze, po ogłoszeniu wyniku pojedynku, ujawnia kartę i sam ogłasza wynik. Silniejszy od rewolwerowca. Nie może zadekretować remisu — musi wskazać jedną osobę, która zginie.",
  },
  {
    id: "uwodziciel",
    name: "Uwodziciel",
    faction: "miasto",
    tier: "kontrowersyjna",
    nightUse: "zerowa",
    selfTarget: false,
    desc: "Zerowej nocy uwodzi wybraną osobę. Ta nie może działać na jego szkodę: nawoływać do jego zabicia, głosować za tym, musi głosować za nim w pojedynkach i nie może ujawnić, że została uwiedziona.",
  },
  {
    id: "mieszczanin",
    name: "Obywatel miasta",
    faction: "miasto",
    tier: "szeregowy",
    filler: true,
    nightUse: "brak",
    desc: "Zwykły mieszkaniec Bum-bum City bez zdolności nocnych. Głosuje, dyskutuje i pojedynkuje się.",
  },

  // ── Bandyci ──────────────────────────────────────────────────────────────
  {
    id: "herszt",
    name: "Herszt",
    faction: "bandyci",
    tier: "kluczowa",
    leader: true,
    nightUse: "brak",
    desc: "Najwyższy rangą bandyta. Na początku gry posiada posążek i decyduje o przydziale posążka w bandzie.",
  },
  {
    id: "msciciel",
    name: "Mściciel",
    faction: "bandyci",
    tier: "tradycyjna",
    nightUse: "raz",
    jawne: true,
    desc: "Raz w grze zabija w nocy wybraną osobę.",
  },
  {
    id: "zlodziej",
    name: "Złodziej",
    faction: "bandyci",
    tier: "tradycyjna",
    nightUse: "raz",
    selfTarget: true,
    desc: "Raz w grze próbuje ukraść posążek wybranej osobie. Działanie tajne.",
  },
  {
    id: "zly-rewolwerowiec",
    name: "Zły rewolwerowiec",
    faction: "bandyci",
    tier: "kluczowa",
    nightUse: "brak",
    desc: "Jeśli wynik pojedynku z nierewolwerowcem jest inny niż jego zwycięstwo, Manitou i tak ogłasza zwycięstwo rewolwerowca.",
  },
  {
    id: "szantazysta",
    name: "Szantażysta",
    faction: "bandyci",
    tier: "kontrowersyjna",
    nightUse: "zerowa",
    selfTarget: false,
    desc: "Zerowej nocy wybiera szantażowanego. Ta osoba nie może działać na jego szkodę ani ujawnić szantażu, musi głosować za nim w pojedynkach.",
  },
  {
    id: "szuler",
    name: "Szuler",
    faction: "bandyci",
    tier: "zwykla",
    nightUse: "raz",
    jawne: true,
    desc: "Raz w grze wybiera osobę do gry w karty — nie budzi się ona tej nocy (choć można ją zabić). Jeśli miała posążek, szuler go wygrywa.",
  },
  {
    id: "bandyta",
    name: "Bandyta",
    faction: "bandyci",
    tier: "szeregowy",
    filler: true,
    nightUse: "brak",
    desc: "Szeregowy członek bandy. Budzi się z bandą, uczestniczy w kradzieży i decyzji o odpłynięciu.",
  },

  // ── Indianie ─────────────────────────────────────────────────────────────
  {
    id: "wodz",
    name: "Wódz",
    faction: "indianie",
    tier: "tradycyjna",
    leader: true,
    nightUse: "brak",
    desc: "Najwyższy rangą Indianin. Rozstrzyga spory w plemieniu i przydziela posążek.",
  },
  {
    id: "szaman",
    name: "Szaman",
    faction: "indianie",
    tier: "kluczowa",
    nightUse: "raz",
    desc: "Raz w grze wpada w trans i poznaje kartę jednej osoby. Działanie tajne.",
  },
  {
    id: "szamanka",
    name: "Szamanka",
    faction: "indianie",
    tier: "zwykla",
    nightUse: "raz",
    desc: "Raz w grze podkłada komuś truciznę. Następnego dnia, przed głosowaniami, ta osoba zielenieje i ginie. Jeśli otruty był ostatnim nie-Indianinem z posążkiem, wygrywa miasto.",
  },
  {
    id: "samotny-kojot",
    name: "Samotny kojot",
    faction: "indianie",
    tier: "zwykla",
    nightUse: "warunkowa",
    desc: "Jeżeli jest jedynym aktywnym Indianinem, zabija dodatkowo jedną osobę.",
  },
  {
    id: "wojownik",
    name: "Wojownik",
    faction: "indianie",
    tier: "zwykla",
    nightUse: "warunkowa",
    desc: "Jeżeli danej nocy Indianie przejęli posążek, a wojownik jest aktywny, zabija dodatkowo jedną osobę.",
  },
  {
    id: "lornecie-oko",
    name: "Lornecie oko",
    faction: "indianie",
    tier: "zwykla",
    nightUse: "raz",
    desc: "Raz w grze dowiaduje się, gdzie znajduje się posążek. Działanie tajne.",
  },
  {
    id: "cicha-stopa",
    name: "Cicha stopa",
    faction: "indianie",
    tier: "kontrowersyjna",
    nightUse: "warunkowa",
    desc: "Mając posążek, może podłożyć go wybranej osobie — jest traktowana jak właściciel, ale o tym nie wie. Jeśli go nie utraci do kolejnego ruchu Indian, cicha stopa może posążek odebrać.",
  },
  {
    id: "indianin",
    name: "Indianin",
    faction: "indianie",
    tier: "szeregowy",
    filler: true,
    nightUse: "brak",
    desc: "Szeregowy wojownik plemienia. Budzi się z Indianami i uczestniczy w nocnym zabójstwie.",
  },

  // ── Ufoki ────────────────────────────────────────────────────────────────
  {
    id: "wielki-ufol",
    name: "Wielki Ufol",
    faction: "ufoki",
    tier: "zwykla",
    leader: true,
    nightUse: "brak",
    desc: "Najwyższy rangą ufol. Decyduje w sprawach spornych i przydziela posążek.",
  },
  {
    id: "zielona-macka",
    name: "Zielona Macka",
    faction: "ufoki",
    tier: "zwykla",
    nightUse: "raz",
    jawne: true,
    desc: "Raz w grze zabija wybraną osobę.",
  },
  {
    id: "detektor",
    name: "Detektor",
    faction: "ufoki",
    tier: "zwykla",
    nightUse: "co-noc",
    desc: "Co noc wybiera osobę, od której zaczyna detekcję. Jeśli ma ona posążek — dowiaduje się tego. Jeśli nie — poznaje, w którym z dwóch łuków okręgu (wyznaczonych przez badanego i detektora) posążek się znajduje.",
  },
  {
    id: "pozeracz",
    name: "Pożeracz Umysłów",
    faction: "ufoki",
    tier: "zwykla",
    nightUse: "co-noc",
    desc: "Co noc poznaje kartę wybranej osoby. Działanie tajne.",
  },
  {
    id: "ufok",
    name: "Ufok",
    faction: "ufoki",
    tier: "szeregowy",
    filler: true,
    nightUse: "brak",
    desc: "Szeregowy ufoludek. Budzi się z pobratymcami, przeszukuje i nadaje sygnał.",
  },

  // ── Janosik (dodatek domowy, osobna frakcja) ─────────────────────────────
  {
    id: "janosik",
    name: "Janosik",
    faction: "janosik",
    tier: "kontrowersyjna",
    leader: true,
    nightUse: "raz",
    selfTarget: true,
    desc: "Sam sobie frakcja. Raz w grze, w nocy i w tajemnicy, macha ciupagą — wtedy wszyscy się cieszą, ale na wynik gry nie ma to wpływu. Janosik wygrywa wtedy i tylko wtedy, gdy rada miasta go powiesi; wszyscy pozostali wtedy przegrywają. Dopóki żyje, Indianie nie mogą wygrać.",
  },
];

export const ROLE_BY_ID: Record<string, Role> = Object.fromEntries(ROLES.map((r) => [r.id, r]));

export function rolesOf(faction: Faction): Role[] {
  return ROLES.filter((r) => r.faction === faction);
}

/** Frakcja Janosika nie ma szeregowych członków, więc bywa `undefined`. */
export function fillerRole(faction: Faction): Role | undefined {
  return ROLES.find((r) => r.faction === faction && r.filler);
}

export const TIER_LABEL: Record<string, string> = {
  kluczowa: "kluczowa",
  tradycyjna: "tradycyjna",
  kontrowersyjna: "kontrowersyjna",
  zwykla: "opcjonalna",
  szeregowy: "szeregowy",
};
